version: '3'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:6.2.0
    ports:
      - 2181:2181
    env_file:
      - .env
    networks:
      - my-network

  kafka:
    image: confluentinc/cp-kafka:6.2.0
    ports:
      - 9092:9092
    env_file:
      - .env
    depends_on:
      - zookeeper
    networks:
      - my-network


  postgresql:
    image: postgres:latest
    ports:
      - 5433:5432
    env_file:
      - .env
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks:
      - my-network

  minio:
    image: minio/minio:latest
    ports:
      - 9000:9000
      - 9001:9001
    env_file:
      - .env
    volumes:
      - ./data:/data
    networks:
      - my-network
    command: server --address ":9000" --console-address ":9001" /data

  scheduler:
    image: scheduler:latest
    ports:
      - 8000:8000
    depends_on:
      - zookeeper
      - postgresql
      - kafka
      - minio
    volumes:
      - ./scheduler:/app/config
    env_file:
      - .env
    networks:
      - my-network
    command: bash -c 'sleep 10 && python -u scheduler.py'

  converter-worker-1:
    image: converter:latest
    depends_on:
      - zookeeper
      - postgresql
      - kafka
      - minio
    volumes:
      - ./executor:/app
    env_file:
      - .env
    networks:
      - my-network
    environment:
      - PARTITION_NUMBER=0
    command: bash -c 'sleep 10 && python -u executor.py'

  converter-worker-2:
    image: converter:latest
    depends_on:
      - zookeeper
      - postgresql
      - kafka
      - minio
    volumes:
      - ./executor:/app
    env_file:
      - .env
    networks:
      - my-network
    environment:
      - PARTITION_NUMBER=1
    command: bash -c 'sleep 10 && python -u executor.py'

networks:
  my-network:
